-- studynewads seed data
-- ~15 real, notable digital ad campaigns from the last 2 years, added by hand
-- so the site isn't empty before the Gumloop pipeline is wired up.
-- Generated from data/seed-ads.json — edit that file and regenerate rather
-- than hand-editing this one.

insert into public.ads (slug, brand, headline, dek, vertical, platforms, format, launch_date, still_running, media_url, media_type, advertiser_page_url, body_copy, copy_notes, origin, sources, is_published)
values
  ('duolingo-dua-lipa-2024', 'Duolingo', 'Learn a language, or the owl finds you', 'Mascot-driven brand stunt', 'edtech', array['instagram', 'tiktok'], 'reel', '2024-04-01', false, '/seed/duolingo-dua-lipa-2024.svg', 'image', 'https://www.duolingo.com', 'Duo missed you.', 'Duolingo extended its unhinged-mascot bit — including a staged ''death'' of Duo the owl and a cameo-style tie-in around Dua Lipa''s album cycle — leaning entirely on organic-feeling stunts rather than traditional media spend. The strategy mirrors the brand''s long-running approach of treating its app-store notifications and social account as the actual ad unit.', 'seed', '[{"label":"Duolingo — official site","url":"https://www.duolingo.com"},{"label":"Ad Age — industry coverage","url":"https://adage.com"}]'::jsonb, true),
  ('cerave-michael-cera-2024', 'CeraVe', 'It''s CeraVe. He''s Michael Cera. Coincidence?', 'Super Bowl skincare launch film', 'skincare', array['meta', 'instagram', 'youtube'], 'video', '2024-02-08', false, '/seed/cerave-michael-cera-2024.svg', 'image', 'https://www.cerave.com', 'Developed with dermatologists. Also, apparently, with Michael Cera.', 'CeraVe built a mockumentary-style campaign around the coincidence of Michael Cera''s name, running teaser content for weeks before revealing the joke in a Super Bowl spot. It''s a rare case of a clinical, dermatologist-endorsed skincare brand using absurdist celebrity comedy instead of the category''s usual efficacy-first messaging.', 'seed', '[{"label":"CeraVe — official site","url":"https://www.cerave.com"},{"label":"AdWeek — industry coverage","url":"https://www.adweek.com"}]'::jsonb, true),
  ('state-farm-jake-2024', 'State Farm', 'Like a good neighbor, Jake is there', 'Long-running mascot campaign refresh', 'insurance', array['meta', 'instagram', 'youtube'], 'video', '2024-03-15', true, '/seed/state-farm-jake-2024.svg', 'image', 'https://www.statefarm.com', 'Jake from State Farm knows a thing or two, because he''s seen a thing or two.', 'State Farm continued to lean on its ''Jake from State Farm'' character, pairing him with athlete cameos across digital cutdowns rather than a single hero spot. The insurer''s decade-plus consistency with the same mascot is unusual in a category that typically rotates spokespeople every few years.', 'seed', '[{"label":"State Farm — official site","url":"https://www.statefarm.com"},{"label":"Marketing Dive — industry coverage","url":"https://www.marketingdive.com"}]'::jsonb, true),
  ('liquid-death-convicted-2024', 'Liquid Death', 'Convicted of loving Liquid Death too much', 'Stunt-marketing beverage brand', 'beverage', array['instagram', 'tiktok'], 'video', '2024-06-10', false, '/seed/liquid-death-convicted-2024.svg', 'image', 'https://liquiddeath.com', 'Murder your thirst.', 'Liquid Death cast real people who had been fired, arrested, or otherwise gotten in trouble for their devotion to the brand, framing canned water with the visual language of a heavy-metal energy drink. The joke only works because the product itself is unglamorous — comedy is doing the differentiation that flavor or price would do for a normal beverage brand.', 'seed', '[{"label":"Liquid Death — official site","url":"https://liquiddeath.com"},{"label":"Ad Age — industry coverage","url":"https://adage.com"}]'::jsonb, true),
  ('poppi-super-bowl-2025', 'Poppi', 'The soda that loves your gut back', 'Prebiotic soda, Super Bowl push', 'beverage', array['meta', 'instagram', 'tiktok'], 'video', '2025-02-09', false, '/seed/poppi-super-bowl-2025.svg', 'image', 'https://drinkpoppi.com', 'Gut health, but make it a soda aisle.', 'Poppi paired a Super Bowl broadcast spot with a QR-code vending stunt at the stadium, betting that a functional-beverage pitch (prebiotics, low sugar) could work inside a category historically sold on nostalgia and taste. The stunt drew as much commentary for its execution and subsequent backlash as for the ad itself, a reminder that experiential add-ons carry their own reputational risk.', 'seed', '[{"label":"Poppi — official site","url":"https://drinkpoppi.com"},{"label":"AdWeek — industry coverage","url":"https://www.adweek.com"}]'::jsonb, true),
  ('mint-mobile-ryan-reynolds-2024', 'Mint Mobile', 'Premium wireless. Shockingly cheap.', 'Founder-as-spokesperson telecom ads', 'telecom', array['meta', 'instagram', 'youtube'], 'video', '2024-05-20', true, '/seed/mint-mobile-ryan-reynolds-2024.svg', 'image', 'https://www.mintmobile.com', 'I own this company. I''m also in the ad. Please buy a plan.', 'Mint Mobile kept running low-budget-styled Ryan Reynolds cutdowns direct-to-camera, a format built to look inexpensive on purpose — the joke is part of the pitch that the carrier passes savings to customers. The ongoing cadence of short, meme-ready clips is built for the Ad Library format as much as for TV.', 'seed', '[{"label":"Mint Mobile — official site","url":"https://www.mintmobile.com"},{"label":"Marketing Dive — industry coverage","url":"https://www.marketingdive.com"}]'::jsonb, true),
  ('openai-chatgpt-super-bowl-2025', 'OpenAI', 'The dawn of a new AI', 'OpenAI''s first-ever brand ad', 'ai-tool', array['youtube', 'meta'], 'video', '2025-02-09', false, '/seed/openai-chatgpt-super-bowl-2025.svg', 'image', 'https://openai.com', 'Intelligence, arriving.', 'OpenAI''s first paid Super Bowl spot leaned on sweeping, humanist imagery rather than a product demo, treating ChatGPT as a moment-of-history event instead of a software feature. It''s a notable pivot for a company that grew almost entirely on word-of-mouth and developer buzz, now buying attention alongside legacy consumer brands.', 'seed', '[{"label":"OpenAI — official site","url":"https://openai.com"},{"label":"Ad Age — industry coverage","url":"https://adage.com"}]'::jsonb, true),
  ('perplexity-ask-anything-2024', 'Perplexity', 'Skip the search. Get the answer.', 'AI answer engine, challenger positioning', 'ai-tool', array['meta', 'instagram'], 'image', '2024-09-12', true, '/seed/perplexity-ask-anything-2024.svg', 'image', 'https://www.perplexity.ai', 'Search, but it actually answers you.', 'Perplexity''s paid social creative positions the product directly against traditional search — screenshots of a cluttered results page next to a clean cited answer — rather than explaining what an ''AI answer engine'' is from scratch. The direct-comparison format is a common challenger-brand move: define yourself by what you replace, not what you are.', 'seed', '[{"label":"Perplexity — official site","url":"https://www.perplexity.ai"},{"label":"TechCrunch — industry coverage","url":"https://techcrunch.com"}]'::jsonb, true),
  ('robinhood-gold-card-2024', 'Robinhood', 'The card that pays you back', 'Fintech premium-tier product launch', 'fintech', array['meta', 'instagram'], 'carousel', '2024-05-08', false, '/seed/robinhood-gold-card-2024.svg', 'image', 'https://robinhood.com', '3% back on everything. No categories. No caps.', 'Robinhood''s Gold Card launch ads used a waitlist-and-scarcity framing — a physical card with a visible serial number — to borrow the cachet of exclusive credit products while undercutting them on cash-back terms. The creative deliberately looks like a luxury-card ad, a departure from Robinhood''s earlier, more utilitarian trading-app messaging.', 'seed', '[{"label":"Robinhood — official site","url":"https://robinhood.com"},{"label":"TechCrunch — industry coverage","url":"https://techcrunch.com"}]'::jsonb, true),
  ('cash-app-block-2024', 'Cash App', 'Money moves different here', 'P2P payments, culture-first creative', 'fintech', array['instagram', 'tiktok'], 'video', '2024-11-01', false, '/seed/cash-app-block-2024.svg', 'image', 'https://cash.app', 'Cash Card. Cash Boost. Cash in hand.', 'Cash App''s creative continues to run through artist and creator partnerships rather than product-feature explainers, treating the Cash Card''s design drops as a cultural object first and a debit card second. The approach mirrors streetwear marketing more than fintech marketing, which is part of how the brand differentiates from Venmo and Zelle.', 'seed', '[{"label":"Cash App — official site","url":"https://cash.app"},{"label":"Marketing Dive — industry coverage","url":"https://www.marketingdive.com"}]'::jsonb, true),
  ('whoop-4-unlock-2024', 'Whoop', 'Unlock your body''s data', 'Wearable fitness tracker, subscription model', 'fitness', array['instagram', 'youtube'], 'video', '2024-05-08', true, '/seed/whoop-4-unlock-2024.svg', 'image', 'https://www.whoop.com', 'No screen. No distractions. Just data that matters.', 'Whoop''s ads foreground recovery and strain scores over step counts, targeting a more data-literate fitness audience than the broader wearables market. The subscription-hardware model (the band itself is nominally free with membership) is unusual enough that a chunk of the creative has to do the work of explaining the business model, not just the device.', 'seed', '[{"label":"Whoop — official site","url":"https://www.whoop.com"},{"label":"TechCrunch — industry coverage","url":"https://techcrunch.com"}]'::jsonb, true),
  ('stanley-quencher-2024', 'Stanley', 'The tumbler that survived a burning car', 'UGC-driven virality, legacy brand', 'retail', array['tiktok', 'instagram'], 'video', '2024-01-20', false, '/seed/stanley-quencher-2024.svg', 'image', 'https://www.stanley1913.com', 'Built for the wild. Carried everywhere else.', 'Stanley''s marketing largely amplified a customer''s own viral video of a Quencher tumbler surviving a car fire with the ice inside still intact, rather than originating the moment itself — the brand''s paid media picked up and re-cut existing organic content. It''s a case study in a 100-year-old outdoor-gear company repositioning around limited-edition colorways and collector culture instead of durability alone.', 'seed', '[{"label":"Stanley — official site","url":"https://www.stanley1913.com"},{"label":"Ad Age — industry coverage","url":"https://adage.com"}]'::jsonb, true),
  ('crumbl-weekly-menu-2024', 'Crumbl', 'This week''s flavors are already gone', 'Rotating-menu bakery chain', 'food', array['instagram', 'tiktok'], 'reel', '2024-08-05', true, '/seed/crumbl-weekly-menu-2024.svg', 'image', 'https://crumblcookies.com', 'New flavors, every Monday.', 'Crumbl''s ads are structured entirely around scarcity and a weekly release cadence, mirroring sneaker-drop marketing more than fast-casual food marketing. The rotating menu gives the brand a reason to post new creative every single week without needing a new campaign concept — the calendar is the campaign.', 'seed', '[{"label":"Crumbl — official site","url":"https://crumblcookies.com"},{"label":"Marketing Dive — industry coverage","url":"https://www.marketingdive.com"}]'::jsonb, true),
  ('ag1-foundational-nutrition-2024', 'AG1', 'One scoop, foundational nutrition', 'Wellness subscription, rebrand push', 'wellness', array['instagram', 'youtube'], 'video', '2024-03-01', true, '/seed/ag1-foundational-nutrition-2024.svg', 'image', 'https://drinkag1.com', 'Your daily foundational nutrition supplement.', 'AG1 (formerly Athletic Greens) rebranded around the vaguer, more defensible term ''foundational nutrition'' rather than specific health claims, a common move for supplement brands navigating regulatory scrutiny. Its ad creative leans heavily on subscription-and-ritual framing — the daily scoop as habit — over any single ingredient story.', 'seed', '[{"label":"AG1 — official site","url":"https://drinkag1.com"},{"label":"AdWeek — industry coverage","url":"https://www.adweek.com"}]'::jsonb, true),
  ('instacart-add-to-cart-2024', 'Instacart', 'Add it to the cart', 'Super Bowl grocery-delivery push', 'food-delivery', array['youtube', 'meta'], 'video', '2024-02-08', false, '/seed/instacart-add-to-cart-2024.svg', 'image', 'https://www.instacart.com', 'Whatever the recipe calls for, we''ll bring it.', 'Instacart''s Super Bowl spot built its visual gag around edible art made from grocery items, a way to make a fundamentally logistics-driven service (delivery, routing, warehouses) feel colorful and food-forward on screen. The category''s ads increasingly compete on the emotional register of home cooking rather than convenience or speed alone.', 'seed', '[{"label":"Instacart — official site","url":"https://www.instacart.com"},{"label":"Ad Age — industry coverage","url":"https://adage.com"}]'::jsonb, true)
on conflict (slug) do update set
  brand = excluded.brand,
  headline = excluded.headline,
  dek = excluded.dek,
  vertical = excluded.vertical,
  platforms = excluded.platforms,
  format = excluded.format,
  launch_date = excluded.launch_date,
  still_running = excluded.still_running,
  media_url = excluded.media_url,
  media_type = excluded.media_type,
  advertiser_page_url = excluded.advertiser_page_url,
  body_copy = excluded.body_copy,
  copy_notes = excluded.copy_notes,
  origin = excluded.origin,
  sources = excluded.sources,
  is_published = excluded.is_published;
